# Generated by Django 4.2.11 on 2024-05-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=12)),
                ('instance_type', models.CharField(choices=[('percussion', 'Percussion'), ('woodwind', 'Woodwind'), ('string', 'String'), ('brass', 'Brass'), ('keyboard', 'Keyboard')], default='-------', max_length=50)),
            ],
        ),
    ]
