# Generated by Django 4.2.11 on 2024-05-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='instance_type',
            new_name='instrument_type',
        ),
    ]
